name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # jalan tiap 6 jam
  workflow_dispatch:        # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AlgamOnline
          outputs: dist/snake.svg

      - name: Tampilkan hasil (debug)
        run: ls -R dist || echo "Folder dist kosong"

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
